export const eduTier = [
  {
    "College Tier": 1,
    Course: 1,
    "Marks%": 91,
    Intership: 6,
    "Credit Score": 401,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 2,
    "Marks%": 83,
    Intership: 6,
    "Credit Score": 368,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 2,
    "Marks%": 90,
    Intership: 5,
    "Credit Score": 365,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 1,
    "Marks%": 92,
    Intership: 5,
    "Credit Score": 362,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 2,
    "Marks%": 85,
    Intership: 5,
    "Credit Score": 360,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 2,
    "Marks%": 82,
    Intership: 4,
    "Credit Score": 347,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 1,
    "Marks%": 75,
    Intership: 2,
    "Credit Score": 345,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 1,
    "Marks%": 85,
    Intership: 4,
    "Credit Score": 345,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 1,
    "Marks%": 64,
    Intership: 3,
    "Credit Score": 344,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 1,
    "Marks%": 62,
    Intership: 6,
    "Credit Score": 342,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 1,
    "Marks%": 90,
    Intership: 0,
    "Credit Score": 340,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 1,
    "Marks%": 75,
    Intership: 1,
    "Credit Score": 335,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 1,
    "Marks%": 70,
    Intership: 1,
    "Credit Score": 330,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 1,
    "Marks%": 58,
    Intership: 2,
    "Credit Score": 328,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 1,
    "Marks%": 86,
    Intership: 2,
    "Credit Score": 326,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 3,
    "Marks%": 66,
    Intership: 6,
    "Credit Score": 326,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 1,
    "Marks%": 76,
    Intership: 0,
    "Credit Score": 326,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 2,
    "Marks%": 74,
    Intership: 2,
    "Credit Score": 319,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 1,
    "Marks%": 58,
    Intership: 4,
    "Credit Score": 318,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 1,
    "Marks%": 68,
    Intership: 0,
    "Credit Score": 318,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 2,
    "Marks%": 71,
    Intership: 2,
    "Credit Score": 316,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 1,
    "Marks%": 65,
    Intership: 3,
    "Credit Score": 315,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 2,
    "Marks%": 78,
    Intership: 4,
    "Credit Score": 313,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 2,
    "Marks%": 78,
    Intership: 1,
    "Credit Score": 313,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 2,
    "Marks%": 57,
    Intership: 6,
    "Credit Score": 312,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 2,
    "Marks%": 55,
    Intership: 3,
    "Credit Score": 310,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 1,
    "Marks%": 90,
    Intership: 6,
    "Credit Score": 310,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 2,
    "Marks%": 71,
    Intership: 1,
    "Credit Score": 306,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 1,
    "Marks%": 95,
    Intership: 2,
    "Credit Score": 305,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 3,
    "Marks%": 85,
    Intership: 2,
    "Credit Score": 305,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 4,
    "Marks%": 90,
    Intership: 4,
    "Credit Score": 305,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 1,
    "Marks%": 85,
    Intership: 3,
    "Credit Score": 305,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 2,
    "Marks%": 58,
    Intership: 2,
    "Credit Score": 303,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 2,
    "Marks%": 95,
    Intership: 1,
    "Credit Score": 300,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 4,
    "Marks%": 94,
    Intership: 6,
    "Credit Score": 299,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 1,
    "Marks%": 79,
    Intership: 0,
    "Credit Score": 299,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 1,
    "Marks%": 59,
    Intership: 2,
    "Credit Score": 299,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 2,
    "Marks%": 61,
    Intership: 4,
    "Credit Score": 296,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 2,
    "Marks%": 90,
    Intership: 1,
    "Credit Score": 295,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 2,
    "Marks%": 40,
    Intership: 6,
    "Credit Score": 295,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 1,
    "Marks%": 83,
    Intership: 2,
    "Credit Score": 293,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 2,
    "Marks%": 98,
    Intership: 3,
    "Credit Score": 293,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 4,
    "Marks%": 78,
    Intership: 4,
    "Credit Score": 293,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 3,
    "Marks%": 52,
    Intership: 4,
    "Credit Score": 292,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 1,
    "Marks%": 82,
    Intership: 5,
    "Credit Score": 292,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 4,
    "Marks%": 84,
    Intership: 3,
    "Credit Score": 289,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 3,
    "Marks%": 47,
    Intership: 4,
    "Credit Score": 287,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 2,
    "Marks%": 72,
    Intership: 2,
    "Credit Score": 287,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 3,
    "Marks%": 87,
    Intership: 3,
    "Credit Score": 287,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 1,
    "Marks%": 87,
    Intership: 1,
    "Credit Score": 287,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 1,
    "Marks%": 94,
    Intership: 0,
    "Credit Score": 284,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 3,
    "Marks%": 54,
    Intership: 6,
    "Credit Score": 284,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 3,
    "Marks%": 44,
    Intership: 4,
    "Credit Score": 284,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 3,
    "Marks%": 74,
    Intership: 4,
    "Credit Score": 284,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 1,
    "Marks%": 84,
    Intership: 4,
    "Credit Score": 284,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 1,
    "Marks%": 52,
    Intership: 1,
    "Credit Score": 282,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 3,
    "Marks%": 91,
    Intership: 5,
    "Credit Score": 281,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 2,
    "Marks%": 65,
    Intership: 5,
    "Credit Score": 280,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 1,
    "Marks%": 59,
    Intership: 6,
    "Credit Score": 279,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 1,
    "Marks%": 57,
    Intership: 6,
    "Credit Score": 277,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 1,
    "Marks%": 57,
    Intership: 6,
    "Credit Score": 277,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 2,
    "Marks%": 71,
    Intership: 4,
    "Credit Score": 276,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 2,
    "Marks%": 60,
    Intership: 2,
    "Credit Score": 275,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 2,
    "Marks%": 77,
    Intership: 0,
    "Credit Score": 272,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 2,
    "Marks%": 87,
    Intership: 5,
    "Credit Score": 272,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 4,
    "Marks%": 76,
    Intership: 5,
    "Credit Score": 271,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 4,
    "Marks%": 96,
    Intership: 0,
    "Credit Score": 271,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 1,
    "Marks%": 51,
    Intership: 0,
    "Credit Score": 271,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 1,
    "Marks%": 90,
    Intership: 2,
    "Credit Score": 270,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 4,
    "Marks%": 82,
    Intership: 4,
    "Credit Score": 267,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 4,
    "Marks%": 59,
    Intership: 6,
    "Credit Score": 264,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 3,
    "Marks%": 53,
    Intership: 4,
    "Credit Score": 263,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 2,
    "Marks%": 88,
    Intership: 4,
    "Credit Score": 263,
    Rating: "",
  },
  {
    "College Tier": 1,
    Course: 4,
    "Marks%": 87,
    Intership: 0,
    "Credit Score": 262,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 2,
    "Marks%": 76,
    Intership: 2,
    "Credit Score": 261,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 2,
    "Marks%": 45,
    Intership: 2,
    "Credit Score": 260,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 4,
    "Marks%": 75,
    Intership: 4,
    "Credit Score": 260,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 1,
    "Marks%": 60,
    Intership: 4,
    "Credit Score": 260,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 2,
    "Marks%": 84,
    Intership: 4,
    "Credit Score": 259,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 3,
    "Marks%": 88,
    Intership: 6,
    "Credit Score": 258,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 2,
    "Marks%": 73,
    Intership: 2,
    "Credit Score": 258,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 2,
    "Marks%": 42,
    Intership: 2,
    "Credit Score": 257,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 3,
    "Marks%": 87,
    Intership: 0,
    "Credit Score": 257,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 1,
    "Marks%": 65,
    Intership: 0,
    "Credit Score": 255,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 1,
    "Marks%": 54,
    Intership: 1,
    "Credit Score": 254,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 2,
    "Marks%": 58,
    Intership: 6,
    "Credit Score": 253,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 2,
    "Marks%": 87,
    Intership: 0,
    "Credit Score": 252,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 2,
    "Marks%": 85,
    Intership: 0,
    "Credit Score": 250,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 1,
    "Marks%": 59,
    Intership: 0,
    "Credit Score": 249,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 2,
    "Marks%": 54,
    Intership: 0,
    "Credit Score": 249,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 2,
    "Marks%": 54,
    Intership: 3,
    "Credit Score": 249,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 3,
    "Marks%": 68,
    Intership: 7,
    "Credit Score": 248,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 4,
    "Marks%": 83,
    Intership: 2,
    "Credit Score": 248,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 1,
    "Marks%": 85,
    Intership: 0,
    "Credit Score": 245,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 3,
    "Marks%": 54,
    Intership: 5,
    "Credit Score": 244,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 2,
    "Marks%": 52,
    Intership: 2,
    "Credit Score": 237,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 4,
    "Marks%": 82,
    Intership: 1,
    "Credit Score": 237,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 4,
    "Marks%": 90,
    Intership: 6,
    "Credit Score": 235,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 4,
    "Marks%": 87,
    Intership: 0,
    "Credit Score": 232,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 4,
    "Marks%": 57,
    Intership: 6,
    "Credit Score": 232,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 3,
    "Marks%": 60,
    Intership: 0,
    "Credit Score": 230,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 4,
    "Marks%": 52,
    Intership: 6,
    "Credit Score": 227,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 3,
    "Marks%": 83,
    Intership: 0,
    "Credit Score": 223,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 3,
    "Marks%": 71,
    Intership: 1,
    "Credit Score": 221,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 4,
    "Marks%": 73,
    Intership: 6,
    "Credit Score": 218,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 3,
    "Marks%": 57,
    Intership: 5,
    "Credit Score": 217,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 4,
    "Marks%": 41,
    Intership: 6,
    "Credit Score": 216,
    Rating: "",
  },
  {
    "College Tier": 2,
    Course: 4,
    "Marks%": 50,
    Intership: 2,
    "Credit Score": 215,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 4,
    "Marks%": 95,
    Intership: 0,
    "Credit Score": 210,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 3,
    "Marks%": 21,
    Intership: 4,
    "Credit Score": 201,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 3,
    "Marks%": 84,
    Intership: 0,
    "Credit Score": 194,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 3,
    "Marks%": 71,
    Intership: 1,
    "Credit Score": 191,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 2,
    "Marks%": 52,
    Intership: 0,
    "Credit Score": 187,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 4,
    "Marks%": 71,
    Intership: 0,
    "Credit Score": 186,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 4,
    "Marks%": 59,
    Intership: 1,
    "Credit Score": 184,
    Rating: "",
  },
  {
    "College Tier": 3,
    Course: 4,
    "Marks%": 68,
    Intership: 0,
    "Credit Score": 183,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 3,
    "Marks%": 67,
    Intership: 0,
    "Credit Score": 177,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 4,
    "Marks%": 85,
    Intership: 0,
    "Credit Score": 170,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 4,
    "Marks%": 48,
    Intership: 3,
    "Credit Score": 163,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 4,
    "Marks%": 58,
    Intership: 0,
    "Credit Score": 143,
    Rating: "",
  },
  {
    "College Tier": 4,
    Course: 4,
    "Marks%": 75,
    Intership: 0,
    "Credit Score": 160,
    Rating: "",
  },
];
