const EmpArray = [
  {
    Income: 12345,
    Position: 4,
    Company: 4,
    "Work Exp": 2,
    "Gap/Unemployed": 4,
    Score: 120,
    Rating: "B",
  },
  {
    Income: 11344,
    Position: 4,
    Company: 4,
    "Work Exp": 5,
    "Gap/Unemployed": 5,
    Score: 132.5,
    Rating: "B",
  },
  {
    Income: 14255,
    Position: 3,
    Company: 4,
    "Work Exp": 1,
    "Gap/Unemployed": 4,
    Score: 135,
    Rating: "B",
  },
  {
    Income: 13684,
    Position: 4,
    Company: 4,
    "Work Exp": 5,
    "Gap/Unemployed": 4,
    Score: 135,
    Rating: "B",
  },
  {
    Income: 15212,
    Position: 3,
    Company: 4,
    "Work Exp": 1,
    "Gap/Unemployed": 4,
    Score: 135,
    Rating: "B",
  },
  {
    Income: 19209,
    Position: 4,
    Company: 4,
    "Work Exp": 5,
    "Gap/Unemployed": 1,
    Score: 142.5,
    Rating: "B",
  },
  {
    Income: 12365,
    Position: 3,
    Company: 4,
    "Work Exp": 2,
    "Gap/Unemployed": 2,
    Score: 145,
    Rating: "B",
  },
  {
    Income: 18245,
    Position: 3,
    Company: 4,
    "Work Exp": 2,
    "Gap/Unemployed": 2,
    Score: 145,
    Rating: "B",
  },
  {
    Income: 22833,
    Position: 3,
    Company: 4,
    "Work Exp": 3,
    "Gap/Unemployed": 4,
    Score: 145,
    Rating: "B",
  },
  {
    Income: 24383,
    Position: 4,
    Company: 3,
    "Work Exp": 3,
    "Gap/Unemployed": 4,
    Score: 145,
    Rating: "B",
  },
  {
    Income: 17323,
    Position: 4,
    Company: 4,
    "Work Exp": 6,
    "Gap/Unemployed": 1,
    Score: 147.5,
    Rating: "B",
  },
  {
    Income: 12344,
    Position: 4,
    Company: 4,
    "Work Exp": 8,
    "Gap/Unemployed": 5,
    Score: 147.5,
    Rating: "B",
  },
  {
    Income: 13502,
    Position: 4,
    Company: 3,
    "Work Exp": 4,
    "Gap/Unemployed": 4,
    Score: 150,
    Rating: "B",
  },
  {
    Income: 16708,
    Position: 4,
    Company: 3,
    "Work Exp": 3,
    "Gap/Unemployed": 0,
    Score: 155,
    Rating: "B",
  },
  {
    Income: 22094,
    Position: 3,
    Company: 4,
    "Work Exp": 4,
    "Gap/Unemployed": 1,
    Score: 157.5,
    Rating: "B",
  },
  {
    Income: 22987,
    Position: 4,
    Company: 3,
    "Work Exp": 4,
    "Gap/Unemployed": 0,
    Score: 160,
    Rating: "B",
  },
  {
    Income: 16547,
    Position: 3,
    Company: 3,
    "Work Exp": 1,
    "Gap/Unemployed": 2,
    Score: 160,
    Rating: "B",
  },
  {
    Income: 14578,
    Position: 2,
    Company: 4,
    "Work Exp": 1,
    "Gap/Unemployed": 1,
    Score: 162.5,
    Rating: "B",
  },
  {
    Income: 24704,
    Position: 3,
    Company: 3,
    "Work Exp": 2,
    "Gap/Unemployed": 2,
    Score: 165,
    Rating: "B",
  },
  {
    Income: 20611,
    Position: 3,
    Company: 3,
    "Work Exp": 4,
    "Gap/Unemployed": 4,
    Score: 170,
    Rating: "B",
  },
  {
    Income: 30828,
    Position: 3,
    Company: 4,
    "Work Exp": 2,
    "Gap/Unemployed": 3,
    Score: 172.5,
    Rating: "B",
  },
  {
    Income: 21231,
    Position: 4,
    Company: 2,
    "Work Exp": 4,
    "Gap/Unemployed": 3,
    Score: 172.5,
    Rating: "B",
  },
  {
    Income: 13134,
    Position: 4,
    Company: 2,
    "Work Exp": 4,
    "Gap/Unemployed": 3,
    Score: 172.5,
    Rating: "B",
  },
  {
    Income: 18017,
    Position: 3,
    Company: 4,
    "Work Exp": 8,
    "Gap/Unemployed": 2,
    Score: 175,
    Rating: "B",
  },
  {
    Income: 12645,
    Position: 4,
    Company: 2,
    "Work Exp": 4,
    "Gap/Unemployed": 2,
    Score: 175,
    Rating: "B",
  },
  {
    Income: 48185,
    Position: 3,
    Company: 4,
    "Work Exp": 2,
    "Gap/Unemployed": 2,
    Score: 175,
    Rating: "B",
  },
  {
    Income: 24000,
    Position: 4,
    Company: 3,
    "Work Exp": 8,
    "Gap/Unemployed": 2,
    Score: 175,
    Rating: "B",
  },
  {
    Income: 24162,
    Position: 3,
    Company: 4,
    "Work Exp": 9,
    "Gap/Unemployed": 2,
    Score: 180,
    Rating: "B",
  },
  {
    Income: 41230,
    Position: 3,
    Company: 4,
    "Work Exp": 2,
    "Gap/Unemployed": 0,
    Score: 180,
    Rating: "B",
  },
  {
    Income: 38481,
    Position: 3,
    Company: 4,
    "Work Exp": 3,
    "Gap/Unemployed": 2,
    Score: 180,
    Rating: "B",
  },
  {
    Income: 14318,
    Position: 3,
    Company: 2,
    "Work Exp": 2,
    "Gap/Unemployed": 1,
    Score: 187.5,
    Rating: "B",
  },
  {
    Income: 18535,
    Position: 3,
    Company: 3,
    "Work Exp": 7,
    "Gap/Unemployed": 3,
    Score: 187.5,
    Rating: "B",
  },
  {
    Income: 49265,
    Position: 3,
    Company: 4,
    "Work Exp": 5,
    "Gap/Unemployed": 2,
    Score: 190,
    Rating: "B",
  },
  {
    Income: 11012,
    Position: 3,
    Company: 3,
    "Work Exp": 8,
    "Gap/Unemployed": 4,
    Score: 190,
    Rating: "B",
  },
  {
    Income: 20541,
    Position: 3,
    Company: 3,
    "Work Exp": 8,
    "Gap/Unemployed": 3,
    Score: 192.5,
    Rating: "B",
  },
  {
    Income: 39135,
    Position: 2,
    Company: 4,
    "Work Exp": 1,
    "Gap/Unemployed": 1,
    Score: 192.5,
    Rating: "B",
  },
  {
    Income: 18084,
    Position: 3,
    Company: 2,
    "Work Exp": 6,
    "Gap/Unemployed": 4,
    Score: 200,
    Rating: "BB",
  },
  {
    Income: 23223,
    Position: 3,
    Company: 2,
    "Work Exp": 5,
    "Gap/Unemployed": 1,
    Score: 202.5,
    Rating: "BB",
  },
  {
    Income: 24674,
    Position: 3,
    Company: 3,
    "Work Exp": 10,
    "Gap/Unemployed": 3,
    Score: 202.5,
    Rating: "BB",
  },
  {
    Income: 38393,
    Position: 3,
    Company: 3,
    "Work Exp": 3,
    "Gap/Unemployed": 1,
    Score: 202.5,
    Rating: "BB",
  },
  {
    Income: 27533,
    Position: 3,
    Company: 4,
    "Work Exp": 8,
    "Gap/Unemployed": 3,
    Score: 202.5,
    Rating: "BB",
  },
  {
    Income: 46927,
    Position: 3,
    Company: 3,
    "Work Exp": 4,
    "Gap/Unemployed": 3,
    Score: 202.5,
    Rating: "BB",
  },
  {
    Income: 34737,
    Position: 3,
    Company: 4,
    "Work Exp": 8,
    "Gap/Unemployed": 3,
    Score: 202.5,
    Rating: "BB",
  },
  {
    Income: 46176,
    Position: 3,
    Company: 3,
    "Work Exp": 4,
    "Gap/Unemployed": 3,
    Score: 202.5,
    Rating: "BB",
  },
  {
    Income: 34327,
    Position: 2,
    Company: 4,
    "Work Exp": 4,
    "Gap/Unemployed": 3,
    Score: 202.5,
    Rating: "BB",
  },
  {
    Income: 43470,
    Position: 3,
    Company: 4,
    "Work Exp": 7,
    "Gap/Unemployed": 1,
    Score: 202.5,
    Rating: "BB",
  },
  {
    Income: 10949,
    Position: 3,
    Company: 3,
    "Work Exp": 10,
    "Gap/Unemployed": 2,
    Score: 205,
    Rating: "BB",
  },
  {
    Income: 13111,
    Position: 3,
    Company: 1,
    "Work Exp": 2,
    "Gap/Unemployed": 1,
    Score: 207.5,
    Rating: "BB",
  },
  {
    Income: 25485,
    Position: 3,
    Company: 2,
    "Work Exp": 1,
    "Gap/Unemployed": 3,
    Score: 207.5,
    Rating: "BB",
  },
  {
    Income: 33611,
    Position: 3,
    Company: 3,
    "Work Exp": 4,
    "Gap/Unemployed": 1,
    Score: 207.5,
    Rating: "BB",
  },
  {
    Income: 46392,
    Position: 2,
    Company: 4,
    "Work Exp": 5,
    "Gap/Unemployed": 3,
    Score: 207.5,
    Rating: "BB",
  },
  {
    Income: 12267,
    Position: 4,
    Company: 1,
    "Work Exp": 8,
    "Gap/Unemployed": 4,
    Score: 210,
    Rating: "BB",
  },
  {
    Income: 41848,
    Position: 2,
    Company: 4,
    "Work Exp": 5,
    "Gap/Unemployed": 2,
    Score: 210,
    Rating: "BB",
  },
  {
    Income: 26992,
    Position: 3,
    Company: 3,
    "Work Exp": 5,
    "Gap/Unemployed": 1,
    Score: 212.5,
    Rating: "BB",
  },
  {
    Income: 27283,
    Position: 3,
    Company: 3,
    "Work Exp": 5,
    "Gap/Unemployed": 1,
    Score: 212.5,
    Rating: "BB",
  },
  {
    Income: 46915,
    Position: 2,
    Company: 3,
    "Work Exp": 2,
    "Gap/Unemployed": 2,
    Score: 215,
    Rating: "BB",
  },
  {
    Income: 27374,
    Position: 3,
    Company: 4,
    "Work Exp": 10,
    "Gap/Unemployed": 2,
    Score: 215,
    Rating: "BB",
  },
  {
    Income: 28941,
    Position: 3,
    Company: 3,
    "Work Exp": 7,
    "Gap/Unemployed": 3,
    Score: 217.5,
    Rating: "BB",
  },
  {
    Income: 11982,
    Position: 3,
    Company: 2,
    "Work Exp": 8,
    "Gap/Unemployed": 0,
    Score: 220,
    Rating: "BB",
  },
  {
    Income: 15519,
    Position: 4,
    Company: 1,
    "Work Exp": 9,
    "Gap/Unemployed": 2,
    Score: 220,
    Rating: "BB",
  },
  {
    Income: 26429,
    Position: 2,
    Company: 4,
    "Work Exp": 6,
    "Gap/Unemployed": 0,
    Score: 220,
    Rating: "BB",
  },
  {
    Income: 38741,
    Position: 3,
    Company: 3,
    "Work Exp": 7,
    "Gap/Unemployed": 2,
    Score: 220,
    Rating: "BB",
  },
  {
    Income: 20678,
    Position: 3,
    Company: 2,
    "Work Exp": 9,
    "Gap/Unemployed": 1,
    Score: 222.5,
    Rating: "BB",
  },
  {
    Income: 48744,
    Position: 2,
    Company: 3,
    "Work Exp": 4,
    "Gap/Unemployed": 2,
    Score: 225,
    Rating: "BB",
  },
  {
    Income: 30617,
    Position: 2,
    Company: 4,
    "Work Exp": 8,
    "Gap/Unemployed": 1,
    Score: 227.5,
    Rating: "BB",
  },
  {
    Income: 48443,
    Position: 3,
    Company: 2,
    "Work Exp": 5,
    "Gap/Unemployed": 3,
    Score: 227.5,
    Rating: "BB",
  },
  {
    Income: 47415,
    Position: 3,
    Company: 3,
    "Work Exp": 9,
    "Gap/Unemployed": 3,
    Score: 227.5,
    Rating: "BB",
  },
  {
    Income: 26799,
    Position: 2,
    Company: 4,
    "Work Exp": 8,
    "Gap/Unemployed": 0,
    Score: 230,
    Rating: "BB",
  },
  {
    Income: 27361,
    Position: 2,
    Company: 2,
    "Work Exp": 1,
    "Gap/Unemployed": 1,
    Score: 232.5,
    Rating: "BB",
  },
  {
    Income: 12345,
    Position: 4,
    Company: 4,
    "Work Exp": 5,
    "Gap/Unemployed": 1,
    Score: 232.5,
    Rating: "BB",
  },
  {
    Income: 18642,
    Position: 3,
    Company: 1,
    "Work Exp": 9,
    "Gap/Unemployed": 4,
    Score: 235,
    Rating: "BB",
  },
  {
    Income: 20013,
    Position: 3,
    Company: 1,
    "Work Exp": 10,
    "Gap/Unemployed": 4,
    Score: 240,
    Rating: "BB",
  },
  {
    Income: 26831,
    Position: 3,
    Company: 1,
    "Work Exp": 3,
    "Gap/Unemployed": 2,
    Score: 240,
    Rating: "BB",
  },
  {
    Income: 77014,
    Position: 3,
    Company: 3,
    "Work Exp": 5,
    "Gap/Unemployed": 2,
    Score: 240,
    Rating: "BB",
  },
  {
    Income: 39234,
    Position: 3,
    Company: 1,
    "Work Exp": 4,
    "Gap/Unemployed": 1,
    Score: 247.5,
    Rating: "BB",
  },
  {
    Income: 79218,
    Position: 2,
    Company: 3,
    "Work Exp": 2,
    "Gap/Unemployed": 1,
    Score: 247.5,
    Rating: "BB",
  },
  {
    Income: 45722,
    Position: 2,
    Company: 1,
    "Work Exp": 1,
    "Gap/Unemployed": 2,
    Score: 250,
    Rating: "BB",
  },
  {
    Income: 35795,
    Position: 3,
    Company: 2,
    "Work Exp": 9,
    "Gap/Unemployed": 2,
    Score: 250,
    Rating: "BB",
  },
  {
    Income: 81665,
    Position: 2,
    Company: 3,
    "Work Exp": 2,
    "Gap/Unemployed": 0,
    Score: 250,
    Rating: "BB",
  },
  {
    Income: 32652,
    Position: 3,
    Company: 1,
    "Work Exp": 6,
    "Gap/Unemployed": 3,
    Score: 252.5,
    Rating: "BB",
  },
  {
    Income: 48126,
    Position: 2,
    Company: 2,
    "Work Exp": 6,
    "Gap/Unemployed": 3,
    Score: 252.5,
    Rating: "BB",
  },
  {
    Income: 33919,
    Position: 2,
    Company: 3,
    "Work Exp": 10,
    "Gap/Unemployed": 2,
    Score: 255,
    Rating: "BB",
  },
  {
    Income: 48229,
    Position: 2,
    Company: 1,
    "Work Exp": 3,
    "Gap/Unemployed": 3,
    Score: 257.5,
    Rating: "BB",
  },
  {
    Income: 47966,
    Position: 2,
    Company: 1,
    "Work Exp": 2,
    "Gap/Unemployed": 1,
    Score: 257.5,
    Rating: "BB",
  },
  {
    Income: 34478,
    Position: 2,
    Company: 1,
    "Work Exp": 2,
    "Gap/Unemployed": 1,
    Score: 257.5,
    Rating: "BB",
  },
  {
    Income: 70156,
    Position: 2,
    Company: 3,
    "Work Exp": 4,
    "Gap/Unemployed": 1,
    Score: 257.5,
    Rating: "BB",
  },
  {
    Income: 42166,
    Position: 2,
    Company: 2,
    "Work Exp": 7,
    "Gap/Unemployed": 2,
    Score: 260,
    Rating: "BB",
  },
  {
    Income: 68588,
    Position: 2,
    Company: 3,
    "Work Exp": 5,
    "Gap/Unemployed": 1,
    Score: 262.5,
    Rating: "A",
  },
  {
    Income: 81091,
    Position: 3,
    Company: 2,
    "Work Exp": 6,
    "Gap/Unemployed": 2,
    Score: 265,
    Rating: "A",
  },
  {
    Income: 84300,
    Position: 1,
    Company: 3,
    "Work Exp": 2,
    "Gap/Unemployed": 1,
    Score: 267.5,
    Rating: "A",
  },
  {
    Income: 25762,
    Position: 2,
    Company: 2,
    "Work Exp": 9,
    "Gap/Unemployed": 2,
    Score: 270,
    Rating: "A",
  },
  {
    Income: 91627,
    Position: 2,
    Company: 3,
    "Work Exp": 7,
    "Gap/Unemployed": 2,
    Score: 270,
    Rating: "A",
  },
  {
    Income: 61100,
    Position: 2,
    Company: 3,
    "Work Exp": 7,
    "Gap/Unemployed": 2,
    Score: 270,
    Rating: "A",
  },
  {
    Income: 77921,
    Position: 2,
    Company: 3,
    "Work Exp": 7,
    "Gap/Unemployed": 1,
    Score: 272.5,
    Rating: "A",
  },
  {
    Income: 89300,
    Position: 2,
    Company: 2,
    "Work Exp": 3,
    "Gap/Unemployed": 1,
    Score: 272.5,
    Rating: "A",
  },
  {
    Income: 85828,
    Position: 2,
    Company: 2,
    "Work Exp": 3,
    "Gap/Unemployed": 0,
    Score: 275,
    Rating: "A",
  },
  {
    Income: 87372,
    Position: 3,
    Company: 1,
    "Work Exp": 4,
    "Gap/Unemployed": 2,
    Score: 275,
    Rating: "A",
  },
  {
    Income: 61510,
    Position: 2,
    Company: 3,
    "Work Exp": 8,
    "Gap/Unemployed": 2,
    Score: 275,
    Rating: "A",
  },
  {
    Income: 29957,
    Position: 2,
    Company: 2,
    "Work Exp": 10,
    "Gap/Unemployed": 1,
    Score: 277.5,
    Rating: "A",
  },
  {
    Income: 29303,
    Position: 2,
    Company: 2,
    "Work Exp": 10,
    "Gap/Unemployed": 1,
    Score: 277.5,
    Rating: "A",
  },
  {
    Income: 95524,
    Position: 2,
    Company: 3,
    "Work Exp": 8,
    "Gap/Unemployed": 1,
    Score: 277.5,
    Rating: "A",
  },
  {
    Income: 76189,
    Position: 2,
    Company: 2,
    "Work Exp": 4,
    "Gap/Unemployed": 0,
    Score: 280,
    Rating: "A",
  },
  {
    Income: 53727,
    Position: 1,
    Company: 3,
    "Work Exp": 5,
    "Gap/Unemployed": 2,
    Score: 280,
    Rating: "A",
  },
  {
    Income: 73860,
    Position: 2,
    Company: 3,
    "Work Exp": 9,
    "Gap/Unemployed": 2,
    Score: 280,
    Rating: "A",
  },
  {
    Income: 65351,
    Position: 1,
    Company: 3,
    "Work Exp": 5,
    "Gap/Unemployed": 1,
    Score: 282.5,
    Rating: "A",
  },
  {
    Income: 127484,
    Position: 2,
    Company: 3,
    "Work Exp": 3,
    "Gap/Unemployed": 1,
    Score: 282.5,
    Rating: "A",
  },
  {
    Income: 97515,
    Position: 1,
    Company: 3,
    "Work Exp": 5,
    "Gap/Unemployed": 0,
    Score: 285,
    Rating: "A",
  },
  {
    Income: 57850,
    Position: 1,
    Company: 3,
    "Work Exp": 6,
    "Gap/Unemployed": 2,
    Score: 285,
    Rating: "A",
  },
  {
    Income: 98643,
    Position: 2,
    Company: 3,
    "Work Exp": 10,
    "Gap/Unemployed": 2,
    Score: 285,
    Rating: "A",
  },
  {
    Income: 87026,
    Position: 2,
    Company: 3,
    "Work Exp": 10,
    "Gap/Unemployed": 1,
    Score: 287.5,
    Rating: "A",
  },
  {
    Income: 82959,
    Position: 2,
    Company: 2,
    "Work Exp": 6,
    "Gap/Unemployed": 1,
    Score: 287.5,
    Rating: "A",
  },
  {
    Income: 56893,
    Position: 1,
    Company: 2,
    "Work Exp": 2,
    "Gap/Unemployed": 1,
    Score: 287.5,
    Rating: "A",
  },
  {
    Income: 75656,
    Position: 2,
    Company: 1,
    "Work Exp": 2,
    "Gap/Unemployed": 1,
    Score: 287.5,
    Rating: "A",
  },
  {
    Income: 74851,
    Position: 2,
    Company: 3,
    "Work Exp": 10,
    "Gap/Unemployed": 1,
    Score: 287.5,
    Rating: "A",
  },
  {
    Income: 60426,
    Position: 1,
    Company: 2,
    "Work Exp": 3,
    "Gap/Unemployed": 1,
    Score: 292.5,
    Rating: "A",
  },
  {
    Income: 71159,
    Position: 1,
    Company: 2,
    "Work Exp": 4,
    "Gap/Unemployed": 2,
    Score: 295,
    Rating: "A",
  },
  {
    Income: 83144,
    Position: 2,
    Company: 2,
    "Work Exp": 7,
    "Gap/Unemployed": 0,
    Score: 295,
    Rating: "A",
  },
  {
    Income: 104642,
    Position: 2,
    Company: 2,
    "Work Exp": 2,
    "Gap/Unemployed": 2,
    Score: 295,
    Rating: "A",
  },
  {
    Income: 57906,
    Position: 1,
    Company: 3,
    "Work Exp": 8,
    "Gap/Unemployed": 1,
    Score: 297.5,
    Rating: "A",
  },
  {
    Income: 75844,
    Position: 1,
    Company: 2,
    "Work Exp": 4,
    "Gap/Unemployed": 1,
    Score: 297.5,
    Rating: "A",
  },
  {
    Income: 76917,
    Position: 2,
    Company: 2,
    "Work Exp": 8,
    "Gap/Unemployed": 1,
    Score: 297.5,
    Rating: "A",
  },
  {
    Income: 125296,
    Position: 2,
    Company: 2,
    "Work Exp": 2,
    "Gap/Unemployed": 1,
    Score: 297.5,
    Rating: "A",
  },
  {
    Income: 84495,
    Position: 1,
    Company: 2,
    "Work Exp": 5,
    "Gap/Unemployed": 2,
    Score: 300,
    Rating: "A",
  },
  {
    Income: 77578,
    Position: 2,
    Company: 2,
    "Work Exp": 9,
    "Gap/Unemployed": 2,
    Score: 300,
    Rating: "A",
  },
  {
    Income: 96270,
    Position: 2,
    Company: 1,
    "Work Exp": 5,
    "Gap/Unemployed": 1,
    Score: 302.5,
    Rating: "A",
  },
  {
    Income: 66687,
    Position: 2,
    Company: 1,
    "Work Exp": 5,
    "Gap/Unemployed": 1,
    Score: 302.5,
    Rating: "A",
  },
  {
    Income: 88733,
    Position: 1,
    Company: 1,
    "Work Exp": 2,
    "Gap/Unemployed": 2,
    Score: 305,
    Rating: "A",
  },
  {
    Income: 56445,
    Position: 1,
    Company: 2,
    "Work Exp": 6,
    "Gap/Unemployed": 2,
    Score: 305,
    Rating: "A",
  },
  {
    Income: 62683,
    Position: 2,
    Company: 2,
    "Work Exp": 10,
    "Gap/Unemployed": 2,
    Score: 305,
    Rating: "A",
  },
  {
    Income: 55965,
    Position: 1,
    Company: 1,
    "Work Exp": 2,
    "Gap/Unemployed": 2,
    Score: 305,
    Rating: "A",
  },
  {
    Income: 59541,
    Position: 1,
    Company: 1,
    "Work Exp": 2,
    "Gap/Unemployed": 1,
    Score: 307.5,
    Rating: "A",
  },
  {
    Income: 50142,
    Position: 2,
    Company: 1,
    "Work Exp": 6,
    "Gap/Unemployed": 1,
    Score: 307.5,
    Rating: "A",
  },
  {
    Income: 82718,
    Position: 1,
    Company: 3,
    "Work Exp": 10,
    "Gap/Unemployed": 1,
    Score: 307.5,
    Rating: "A",
  },
  {
    Income: 80467,
    Position: 1,
    Company: 3,
    "Work Exp": 10,
    "Gap/Unemployed": 1,
    Score: 307.5,
    Rating: "A",
  },
  {
    Income: 81095,
    Position: 2,
    Company: 1,
    "Work Exp": 6,
    "Gap/Unemployed": 1,
    Score: 307.5,
    Rating: "A",
  },
  {
    Income: 87003,
    Position: 2,
    Company: 1,
    "Work Exp": 6,
    "Gap/Unemployed": 1,
    Score: 307.5,
    Rating: "A",
  },
  {
    Income: 84976,
    Position: 1,
    Company: 3,
    "Work Exp": 10,
    "Gap/Unemployed": 1,
    Score: 307.5,
    Rating: "A",
  },
  {
    Income: 56174,
    Position: 1,
    Company: 1,
    "Work Exp": 3,
    "Gap/Unemployed": 2,
    Score: 310,
    Rating: "AA",
  },
  {
    Income: 160641,
    Position: 2,
    Company: 3,
    "Work Exp": 8,
    "Gap/Unemployed": 0,
    Score: 310,
    Rating: "AA",
  },
  {
    Income: 94787,
    Position: 1,
    Company: 1,
    "Work Exp": 3,
    "Gap/Unemployed": 1,
    Score: 312.5,
    Rating: "AA",
  },
  {
    Income: 89094,
    Position: 1,
    Company: 2,
    "Work Exp": 8,
    "Gap/Unemployed": 2,
    Score: 315,
    Rating: "AA",
  },
  {
    Income: 65486,
    Position: 1,
    Company: 2,
    "Work Exp": 8,
    "Gap/Unemployed": 2,
    Score: 315,
    Rating: "AA",
  },
  {
    Income: 82526,
    Position: 2,
    Company: 1,
    "Work Exp": 8,
    "Gap/Unemployed": 2,
    Score: 315,
    Rating: "AA",
  },
  {
    Income: 112968,
    Position: 1,
    Company: 2,
    "Work Exp": 2,
    "Gap/Unemployed": 2,
    Score: 315,
    Rating: "AA",
  },
  {
    Income: 103723,
    Position: 2,
    Company: 3,
    "Work Exp": 10,
    "Gap/Unemployed": 2,
    Score: 315,
    Rating: "AA",
  },
  {
    Income: 132455,
    Position: 2,
    Company: 2,
    "Work Exp": 5,
    "Gap/Unemployed": 0,
    Score: 315,
    Rating: "AA",
  },
  {
    Income: 123223,
    Position: 2,
    Company: 1,
    "Work Exp": 2,
    "Gap/Unemployed": 2,
    Score: 315,
    Rating: "AA",
  },
  {
    Income: 57312,
    Position: 1,
    Company: 1,
    "Work Exp": 5,
    "Gap/Unemployed": 2,
    Score: 320,
    Rating: "AA",
  },
  {
    Income: 85481,
    Position: 1,
    Company: 2,
    "Work Exp": 9,
    "Gap/Unemployed": 2,
    Score: 320,
    Rating: "AA",
  },
  {
    Income: 121300,
    Position: 1,
    Company: 2,
    "Work Exp": 2,
    "Gap/Unemployed": 0,
    Score: 320,
    Rating: "AA",
  },
  {
    Income: 73630,
    Position: 2,
    Company: 1,
    "Work Exp": 9,
    "Gap/Unemployed": 1,
    Score: 322.5,
    Rating: "AA",
  },
  {
    Income: 109330,
    Position: 2,
    Company: 1,
    "Work Exp": 4,
    "Gap/Unemployed": 2,
    Score: 325,
    Rating: "AA",
  },
  {
    Income: 101915,
    Position: 2,
    Company: 1,
    "Work Exp": 3,
    "Gap/Unemployed": 0,
    Score: 325,
    Rating: "AA",
  },
  {
    Income: 127102,
    Position: 1,
    Company: 2,
    "Work Exp": 4,
    "Gap/Unemployed": 1,
    Score: 327.5,
    Rating: "AA",
  },
  {
    Income: 95624,
    Position: 2,
    Company: 2,
    "Work Exp": 8,
    "Gap/Unemployed": 1,
    Score: 327.5,
    Rating: "AA",
  },
  {
    Income: 72291,
    Position: 1,
    Company: 1,
    "Work Exp": 8,
    "Gap/Unemployed": 2,
    Score: 335,
    Rating: "AA",
  },
  {
    Income: 102543,
    Position: 2,
    Company: 1,
    "Work Exp": 6,
    "Gap/Unemployed": 2,
    Score: 335,
    Rating: "AA",
  },
  {
    Income: 102756,
    Position: 2,
    Company: 2,
    "Work Exp": 10,
    "Gap/Unemployed": 0,
    Score: 340,
    Rating: "AA",
  },
  {
    Income: 111419,
    Position: 2,
    Company: 1,
    "Work Exp": 7,
    "Gap/Unemployed": 2,
    Score: 340,
    Rating: "AA",
  },
  {
    Income: 156654,
    Position: 2,
    Company: 1,
    "Work Exp": 6,
    "Gap/Unemployed": 0,
    Score: 340,
    Rating: "AA",
  },
  {
    Income: 104287,
    Position: 1,
    Company: 2,
    "Work Exp": 7,
    "Gap/Unemployed": 0,
    Score: 345,
    Rating: "AA",
  },
  {
    Income: 113844,
    Position: 2,
    Company: 1,
    "Work Exp": 8,
    "Gap/Unemployed": 1,
    Score: 347.5,
    Rating: "AA",
  },
  {
    Income: 126060,
    Position: 1,
    Company: 2,
    "Work Exp": 9,
    "Gap/Unemployed": 2,
    Score: 350,
    Rating: "AA",
  },
  {
    Income: 106515,
    Position: 2,
    Company: 1,
    "Work Exp": 8,
    "Gap/Unemployed": 0,
    Score: 350,
    Rating: "AA",
  },
  {
    Income: 142546,
    Position: 2,
    Company: 2,
    "Work Exp": 12,
    "Gap/Unemployed": 0,
    Score: 350,
    Rating: "AA",
  },
  {
    Income: 65000,
    Position: 1,
    Company: 1,
    "Work Exp": 4,
    "Gap/Unemployed": 0,
    Score: 350,
    Rating: "AA",
  },
  {
    Income: 101800,
    Position: 1,
    Company: 2,
    "Work Exp": 10,
    "Gap/Unemployed": 1,
    Score: 357.5,
    Rating: "AA",
  },
  {
    Income: 122497,
    Position: 1,
    Company: 1,
    "Work Exp": 8,
    "Gap/Unemployed": 0,
    Score: 370,
    Rating: "AA",
  },
  {
    Income: 110000,
    Position: 1,
    Company: 2,
    "Work Exp": 12,
    "Gap/Unemployed": 0,
    Score: 370,
    Rating: "AA",
  },
  {
    Income: 106925,
    Position: 1,
    Company: 1,
    "Work Exp": 9,
    "Gap/Unemployed": 0,
    Score: 375,
    Rating: "AA",
  },
];

export default EmpArray;
