export const data = [
  {
    "No. of Connections": 4977,
    "Posts(past month)": 27,
    "Check Ins(past month)": 10,
    Sponsorships: 1,
    Total: 136.655,
    Rating: "AA",
  },
  {
    "No. of Connections": 4162,
    "Posts(past month)": 24,
    "Check Ins(past month)": 8,
    Sponsorships: 1,
    Total: 115.43,
    Rating: "AA",
  },
  {
    "No. of Connections": 3955,
    "Posts(past month)": 25,
    "Check Ins(past month)": 8,
    Sponsorships: 1,
    Total: 113.325,
    Rating: "AA",
  },
  {
    "No. of Connections": 4329,
    "Posts(past month)": 8,
    "Check Ins(past month)": 10,
    Sponsorships: 1,
    Total: 107.935,
    Rating: "AA",
  },
  {
    "No. of Connections": 4612,
    "Posts(past month)": 26,
    "Check Ins(past month)": 2,
    Sponsorships: 0,
    Total: 101.18,
    Rating: "AA",
  },
  {
    "No. of Connections": 3521,
    "Posts(past month)": 18,
    "Check Ins(past month)": 10,
    Sponsorships: 0,
    Total: 100.815,
    Rating: "AA",
  },
  {
    "No. of Connections": 2487,
    "Posts(past month)": 28,
    "Check Ins(past month)": 8,
    Sponsorships: 2,
    Total: 99.305,
    Rating: "AA",
  },
  {
    "No. of Connections": 4377,
    "Posts(past month)": 24,
    "Check Ins(past month)": 3,
    Sponsorships: 0,
    Total: 98.655,
    Rating: "AA",
  },
  {
    "No. of Connections": 2414,
    "Posts(past month)": 26,
    "Check Ins(past month)": 10,
    Sponsorships: 1,
    Total: 97.21,
    Rating: "AA",
  },
  {
    "No. of Connections": 3221,
    "Posts(past month)": 28,
    "Check Ins(past month)": 6,
    Sponsorships: 0,
    Total: 94.315,
    Rating: "AA",
  },
  {
    "No. of Connections": 3174,
    "Posts(past month)": 20,
    "Check Ins(past month)": 7,
    Sponsorships: 1,
    Total: 93.61,
    Rating: "AA",
  },
  {
    "No. of Connections": 4541,
    "Posts(past month)": 2,
    "Check Ins(past month)": 6,
    Sponsorships: 1,
    Total: 93.115,
    Rating: "AA",
  },
  {
    "No. of Connections": 2655,
    "Posts(past month)": 26,
    "Check Ins(past month)": 9,
    Sponsorships: 0,
    Total: 92.825,
    Rating: "AA",
  },
  {
    "No. of Connections": 3917,
    "Posts(past month)": 9,
    "Check Ins(past month)": 8,
    Sponsorships: 0,
    Total: 91.755,
    Rating: "AA",
  },
  {
    "No. of Connections": 4025,
    "Posts(past month)": 8,
    "Check Ins(past month)": 6,
    Sponsorships: 1,
    Total: 91.375,
    Rating: "AA",
  },
  {
    "No. of Connections": 4262,
    "Posts(past month)": 1,
    "Check Ins(past month)": 7,
    Sponsorships: 1,
    Total: 90.93,
    Rating: "AA",
  },
  {
    "No. of Connections": 3323,
    "Posts(past month)": 8,
    "Check Ins(past month)": 9,
    Sponsorships: 1,
    Total: 89.845,
    Rating: "AA",
  },
  {
    "No. of Connections": 4744,
    "Posts(past month)": 4,
    "Check Ins(past month)": 4,
    Sponsorships: 0,
    Total: 87.16,
    Rating: "AA",
  },
  {
    "No. of Connections": 3845,
    "Posts(past month)": 8,
    "Check Ins(past month)": 5,
    Sponsorships: 1,
    Total: 85.675,
    Rating: "AA",
  },
  {
    "No. of Connections": 3248,
    "Posts(past month)": 18,
    "Check Ins(past month)": 6,
    Sponsorships: 0,
    Total: 84.72,
    Rating: "AA",
  },
  {
    "No. of Connections": 1847,
    "Posts(past month)": 28,
    "Check Ins(past month)": 8,
    Sponsorships: 1,
    Total: 84.705,
    Rating: "AA",
  },
  {
    "No. of Connections": 3806,
    "Posts(past month)": 18,
    "Check Ins(past month)": 1,
    Sponsorships: 1,
    Total: 83.09,
    Rating: "AA",
  },
  {
    "No. of Connections": 1982,
    "Posts(past month)": 28,
    "Check Ins(past month)": 8,
    Sponsorships: 0,
    Total: 81.73,
    Rating: "AA",
  },
  {
    "No. of Connections": 2771,
    "Posts(past month)": 14,
    "Check Ins(past month)": 7,
    Sponsorships: 1,
    Total: 81.565,
    Rating: "AA",
  },
  {
    "No. of Connections": 1865,
    "Posts(past month)": 18,
    "Check Ins(past month)": 10,
    Sponsorships: 1,
    Total: 80.975,
    Rating: "AA",
  },
  {
    "No. of Connections": 3387,
    "Posts(past month)": 7,
    "Check Ins(past month)": 6,
    Sponsorships: 1,
    Total: 80.805,
    Rating: "AA",
  },
  {
    "No. of Connections": 1578,
    "Posts(past month)": 27,
    "Check Ins(past month)": 10,
    Sponsorships: 0,
    Total: 80.67,
    Rating: "AA",
  },
  {
    "No. of Connections": 1774,
    "Posts(past month)": 22,
    "Check Ins(past month)": 9,
    Sponsorships: 1,
    Total: 80.61,
    Rating: "AA",
  },
  {
    "No. of Connections": 4177,
    "Posts(past month)": 8,
    "Check Ins(past month)": 3,
    Sponsorships: 0,
    Total: 79.655,
    Rating: "A",
  },
  {
    "No. of Connections": 1237,
    "Posts(past month)": 26,
    "Check Ins(past month)": 10,
    Sponsorships: 1,
    Total: 79.555,
    Rating: "A",
  },
  {
    "No. of Connections": 4431,
    "Posts(past month)": 1,
    "Check Ins(past month)": 4,
    Sponsorships: 0,
    Total: 79.465,
    Rating: "A",
  },
  {
    "No. of Connections": 2218,
    "Posts(past month)": 29,
    "Check Ins(past month)": 4,
    Sponsorships: 1,
    Total: 79.27,
    Rating: "A",
  },
  {
    "No. of Connections": 1693,
    "Posts(past month)": 26,
    "Check Ins(past month)": 7,
    Sponsorships: 1,
    Total: 77.395,
    Rating: "A",
  },
  {
    "No. of Connections": 2753,
    "Posts(past month)": 30,
    "Check Ins(past month)": 0,
    Sponsorships: 1,
    Total: 76.295,
    Rating: "A",
  },
  {
    "No. of Connections": 3750,
    "Posts(past month)": 19,
    "Check Ins(past month)": 0,
    Sponsorships: 0,
    Total: 75.25,
    Rating: "A",
  },
  {
    "No. of Connections": 2882,
    "Posts(past month)": 17,
    "Check Ins(past month)": 5,
    Sponsorships: 0,
    Total: 75.23,
    Rating: "A",
  },
  {
    "No. of Connections": 2469,
    "Posts(past month)": 16,
    "Check Ins(past month)": 7,
    Sponsorships: 0,
    Total: 74.035,
    Rating: "A",
  },
  {
    "No. of Connections": 4588,
    "Posts(past month)": 1,
    "Check Ins(past month)": 1,
    Sponsorships: 0,
    Total: 72.82,
    Rating: "A",
  },
  {
    "No. of Connections": 1516,
    "Posts(past month)": 15,
    "Check Ins(past month)": 10,
    Sponsorships: 1,
    Total: 72.74,
    Rating: "A",
  },
  {
    "No. of Connections": 2237,
    "Posts(past month)": 12,
    "Check Ins(past month)": 9,
    Sponsorships: 0,
    Total: 72.555,
    Rating: "A",
  },
  {
    "No. of Connections": 1152,
    "Posts(past month)": 22,
    "Check Ins(past month)": 9,
    Sponsorships: 1,
    Total: 71.28,
    Rating: "A",
  },
  {
    "No. of Connections": 973,
    "Posts(past month)": 21,
    "Check Ins(past month)": 10,
    Sponsorships: 1,
    Total: 70.595,
    Rating: "A",
  },
  {
    "No. of Connections": 2431,
    "Posts(past month)": 8,
    "Check Ins(past month)": 7,
    Sponsorships: 1,
    Total: 70.465,
    Rating: "A",
  },
  {
    "No. of Connections": 2749,
    "Posts(past month)": 17,
    "Check Ins(past month)": 4,
    Sponsorships: 0,
    Total: 70.235,
    Rating: "A",
  },
  {
    "No. of Connections": 566,
    "Posts(past month)": 29,
    "Check Ins(past month)": 9,
    Sponsorships: 1,
    Total: 69.49,
    Rating: "A",
  },
  {
    "No. of Connections": 2466,
    "Posts(past month)": 29,
    "Check Ins(past month)": 1,
    Sponsorships: 0,
    Total: 68.99,
    Rating: "A",
  },
  {
    "No. of Connections": 2790,
    "Posts(past month)": 12,
    "Check Ins(past month)": 5,
    Sponsorships: 0,
    Total: 68.85,
    Rating: "A",
  },
  {
    "No. of Connections": 1437,
    "Posts(past month)": 29,
    "Check Ins(past month)": 6,
    Sponsorships: 0,
    Total: 68.555,
    Rating: "A",
  },
  {
    "No. of Connections": 610,
    "Posts(past month)": 27,
    "Check Ins(past month)": 9,
    Sponsorships: 1,
    Total: 68.15,
    Rating: "A",
  },
  {
    "No. of Connections": 2921,
    "Posts(past month)": 21,
    "Check Ins(past month)": 1,
    Sponsorships: 0,
    Total: 67.815,
    Rating: "A",
  },
  {
    "No. of Connections": 1965,
    "Posts(past month)": 8,
    "Check Ins(past month)": 10,
    Sponsorships: 0,
    Total: 67.475,
    Rating: "A",
  },
  {
    "No. of Connections": 859,
    "Posts(past month)": 25,
    "Check Ins(past month)": 8,
    Sponsorships: 1,
    Total: 66.885,
    Rating: "A",
  },
  {
    "No. of Connections": 2848,
    "Posts(past month)": 13,
    "Check Ins(past month)": 2,
    Sponsorships: 1,
    Total: 66.72,
    Rating: "A",
  },
  {
    "No. of Connections": 2153,
    "Posts(past month)": 26,
    "Check Ins(past month)": 1,
    Sponsorships: 1,
    Total: 66.295,
    Rating: "A",
  },
  {
    "No. of Connections": 1845,
    "Posts(past month)": 6,
    "Check Ins(past month)": 9,
    Sponsorships: 1,
    Total: 65.675,
    Rating: "A",
  },
  {
    "No. of Connections": 3089,
    "Posts(past month)": 4,
    "Check Ins(past month)": 5,
    Sponsorships: 0,
    Total: 65.335,
    Rating: "A",
  },
  {
    "No. of Connections": 1342,
    "Posts(past month)": 27,
    "Check Ins(past month)": 6,
    Sponsorships: 0,
    Total: 65.13,
    Rating: "A",
  },
  {
    "No. of Connections": 3489,
    "Posts(past month)": 9,
    "Check Ins(past month)": 1,
    Sponsorships: 0,
    Total: 64.335,
    Rating: "A",
  },
  {
    "No. of Connections": 1677,
    "Posts(past month)": 18,
    "Check Ins(past month)": 7,
    Sponsorships: 0,
    Total: 64.155,
    Rating: "A",
  },
  {
    "No. of Connections": 2069,
    "Posts(past month)": 9,
    "Check Ins(past month)": 8,
    Sponsorships: 0,
    Total: 64.035,
    Rating: "A",
  },
  {
    "No. of Connections": 1784,
    "Posts(past month)": 23,
    "Check Ins(past month)": 3,
    Sponsorships: 1,
    Total: 63.76,
    Rating: "A",
  },
  {
    "No. of Connections": 1378,
    "Posts(past month)": 11,
    "Check Ins(past month)": 9,
    Sponsorships: 1,
    Total: 63.67,
    Rating: "A",
  },
  {
    "No. of Connections": 2347,
    "Posts(past month)": 18,
    "Check Ins(past month)": 3,
    Sponsorships: 0,
    Total: 62.205,
    Rating: "A",
  },
  {
    "No. of Connections": 338,
    "Posts(past month)": 22,
    "Check Ins(past month)": 10,
    Sponsorships: 1,
    Total: 62.07,
    Rating: "A",
  },
  {
    "No. of Connections": 2062,
    "Posts(past month)": 1,
    "Check Ins(past month)": 10,
    Sponsorships: 0,
    Total: 61.93,
    Rating: "A",
  },
  {
    "No. of Connections": 1128,
    "Posts(past month)": 22,
    "Check Ins(past month)": 6,
    Sponsorships: 1,
    Total: 61.92,
    Rating: "A",
  },
  {
    "No. of Connections": 2192,
    "Posts(past month)": 3,
    "Check Ins(past month)": 7,
    Sponsorships: 1,
    Total: 61.88,
    Rating: "A",
  },
  {
    "No. of Connections": 1123,
    "Posts(past month)": 28,
    "Check Ins(past month)": 4,
    Sponsorships: 1,
    Total: 61.845,
    Rating: "A",
  },
  {
    "No. of Connections": 3251,
    "Posts(past month)": 1,
    "Check Ins(past month)": 4,
    Sponsorships: 0,
    Total: 61.765,
    Rating: "A",
  },
  {
    "No. of Connections": 1530,
    "Posts(past month)": 18,
    "Check Ins(past month)": 5,
    Sponsorships: 1,
    Total: 60.95,
    Rating: "A",
  },
  {
    "No. of Connections": 2447,
    "Posts(past month)": 18,
    "Check Ins(past month)": 2,
    Sponsorships: 0,
    Total: 60.705,
    Rating: "A",
  },
  {
    "No. of Connections": 1099,
    "Posts(past month)": 12,
    "Check Ins(past month)": 9,
    Sponsorships: 1,
    Total: 60.485,
    Rating: "A",
  },
  {
    "No. of Connections": 792,
    "Posts(past month)": 19,
    "Check Ins(past month)": 8,
    Sponsorships: 1,
    Total: 59.88,
    Rating: "BB",
  },
  {
    "No. of Connections": 947,
    "Posts(past month)": 13,
    "Check Ins(past month)": 9,
    Sponsorships: 1,
    Total: 59.205,
    Rating: "BB",
  },
  {
    "No. of Connections": 997,
    "Posts(past month)": 20,
    "Check Ins(past month)": 8,
    Sponsorships: 0,
    Total: 58.955,
    Rating: "BB",
  },
  {
    "No. of Connections": 3824,
    "Posts(past month)": 1,
    "Check Ins(past month)": 0,
    Sponsorships: 0,
    Total: 58.36,
    Rating: "BB",
  },
  {
    "No. of Connections": 881,
    "Posts(past month)": 15,
    "Check Ins(past month)": 10,
    Sponsorships: 0,
    Total: 58.215,
    Rating: "BB",
  },
  {
    "No. of Connections": 853,
    "Posts(past month)": 27,
    "Check Ins(past month)": 6,
    Sponsorships: 0,
    Total: 57.795,
    Rating: "BB",
  },
  {
    "No. of Connections": 1091,
    "Posts(past month)": 9,
    "Check Ins(past month)": 9,
    Sponsorships: 1,
    Total: 57.365,
    Rating: "BB",
  },
  {
    "No. of Connections": 1833,
    "Posts(past month)": 18,
    "Check Ins(past month)": 2,
    Sponsorships: 1,
    Total: 56.495,
    Rating: "BB",
  },
  {
    "No. of Connections": 1473,
    "Posts(past month)": 2,
    "Check Ins(past month)": 9,
    Sponsorships: 1,
    Total: 56.095,
    Rating: "BB",
  },
  {
    "No. of Connections": 397,
    "Posts(past month)": 15,
    "Check Ins(past month)": 10,
    Sponsorships: 1,
    Total: 55.955,
    Rating: "BB",
  },
  {
    "No. of Connections": 1577,
    "Posts(past month)": 27,
    "Check Ins(past month)": 0,
    Sponsorships: 1,
    Total: 55.655,
    Rating: "BB",
  },
  {
    "No. of Connections": 174,
    "Posts(past month)": 23,
    "Check Ins(past month)": 10,
    Sponsorships: 0,
    Total: 55.61,
    Rating: "BB",
  },
  {
    "No. of Connections": 633,
    "Posts(past month)": 19,
    "Check Ins(past month)": 9,
    Sponsorships: 0,
    Total: 55.495,
    Rating: "BB",
  },
  {
    "No. of Connections": 2396,
    "Posts(past month)": 13,
    "Check Ins(past month)": 2,
    Sponsorships: 0,
    Total: 54.94,
    Rating: "BB",
  },
  {
    "No. of Connections": 1502,
    "Posts(past month)": 18,
    "Check Ins(past month)": 3,
    Sponsorships: 1,
    Total: 54.53,
    Rating: "BB",
  },
  {
    "No. of Connections": 2531,
    "Posts(past month)": 16,
    "Check Ins(past month)": 0,
    Sponsorships: 0,
    Total: 53.965,
    Rating: "BB",
  },
  {
    "No. of Connections": 843,
    "Posts(past month)": 30,
    "Check Ins(past month)": 2,
    Sponsorships: 1,
    Total: 53.645,
    Rating: "BB",
  },
  {
    "No. of Connections": 1833,
    "Posts(past month)": 23,
    "Check Ins(past month)": 1,
    Sponsorships: 0,
    Total: 53.495,
    Rating: "BB",
  },
  {
    "No. of Connections": 562,
    "Posts(past month)": 22,
    "Check Ins(past month)": 6,
    Sponsorships: 1,
    Total: 53.43,
    Rating: "BB",
  },
  {
    "No. of Connections": 2957,
    "Posts(past month)": 1,
    "Check Ins(past month)": 1,
    Sponsorships: 1,
    Total: 53.355,
    Rating: "BB",
  },
  {
    "No. of Connections": 2940,
    "Posts(past month)": 1,
    "Check Ins(past month)": 1,
    Sponsorships: 1,
    Total: 53.1,
    Rating: "BB",
  },
  {
    "No. of Connections": 453,
    "Posts(past month)": 28,
    "Check Ins(past month)": 6,
    Sponsorships: 0,
    Total: 52.795,
    Rating: "BB",
  },
  {
    "No. of Connections": 919,
    "Posts(past month)": 15,
    "Check Ins(past month)": 6,
    Sponsorships: 1,
    Total: 51.785,
    Rating: "BB",
  },
  {
    "No. of Connections": 842,
    "Posts(past month)": 19,
    "Check Ins(past month)": 5,
    Sponsorships: 1,
    Total: 51.63,
    Rating: "BB",
  },
  {
    "No. of Connections": 3171,
    "Posts(past month)": 0,
    "Check Ins(past month)": 1,
    Sponsorships: 0,
    Total: 50.565,
    Rating: "BB",
  },
  {
    "No. of Connections": 708,
    "Posts(past month)": 18,
    "Check Ins(past month)": 7,
    Sponsorships: 0,
    Total: 49.62,
    Rating: "BB",
  },
  {
    "No. of Connections": 1169,
    "Posts(past month)": 5,
    "Check Ins(past month)": 7,
    Sponsorships: 1,
    Total: 48.535,
    Rating: "BB",
  },
  {
    "No. of Connections": 833,
    "Posts(past month)": 4,
    "Check Ins(past month)": 9,
    Sponsorships: 1,
    Total: 48.495,
    Rating: "BB",
  },
  {
    "No. of Connections": 1154,
    "Posts(past month)": 25,
    "Check Ins(past month)": 2,
    Sponsorships: 0,
    Total: 48.31,
    Rating: "BB",
  },
  {
    "No. of Connections": 2617,
    "Posts(past month)": 9,
    "Check Ins(past month)": 0,
    Sponsorships: 0,
    Total: 48.255,
    Rating: "BB",
  },
  {
    "No. of Connections": 1264,
    "Posts(past month)": 12,
    "Check Ins(past month)": 4,
    Sponsorships: 1,
    Total: 47.96,
    Rating: "BB",
  },
  {
    "No. of Connections": 374,
    "Posts(past month)": 24,
    "Check Ins(past month)": 6,
    Sponsorships: 0,
    Total: 47.61,
    Rating: "BB",
  },
  {
    "No. of Connections": 763,
    "Posts(past month)": 15,
    "Check Ins(past month)": 7,
    Sponsorships: 0,
    Total: 47.445,
    Rating: "BB",
  },
  {
    "No. of Connections": 547,
    "Posts(past month)": 30,
    "Check Ins(past month)": 3,
    Sponsorships: 0,
    Total: 47.205,
    Rating: "BB",
  },
  {
    "No. of Connections": 917,
    "Posts(past month)": 9,
    "Check Ins(past month)": 8,
    Sponsorships: 0,
    Total: 46.755,
    Rating: "BB",
  },
  {
    "No. of Connections": 681,
    "Posts(past month)": 13,
    "Check Ins(past month)": 6,
    Sponsorships: 1,
    Total: 46.215,
    Rating: "BB",
  },
  {
    "No. of Connections": 282,
    "Posts(past month)": 30,
    "Check Ins(past month)": 2,
    Sponsorships: 1,
    Total: 45.23,
    Rating: "BB",
  },
  {
    "No. of Connections": 1201,
    "Posts(past month)": 15,
    "Check Ins(past month)": 4,
    Sponsorships: 0,
    Total: 45.015,
    Rating: "BB",
  },
  {
    "No. of Connections": 1721,
    "Posts(past month)": 10,
    "Check Ins(past month)": 3,
    Sponsorships: 0,
    Total: 44.815,
    Rating: "BB",
  },
  {
    "No. of Connections": 951,
    "Posts(past month)": 1,
    "Check Ins(past month)": 8,
    Sponsorships: 1,
    Total: 44.265,
    Rating: "BB",
  },
  {
    "No. of Connections": 612,
    "Posts(past month)": 14,
    "Check Ins(past month)": 5,
    Sponsorships: 1,
    Total: 43.18,
    Rating: "BB",
  },
  {
    "No. of Connections": 212,
    "Posts(past month)": 17,
    "Check Ins(past month)": 6,
    Sponsorships: 1,
    Total: 43.18,
    Rating: "BB",
  },
  {
    "No. of Connections": 745,
    "Posts(past month)": 8,
    "Check Ins(past month)": 8,
    Sponsorships: 0,
    Total: 43.175,
    Rating: "BB",
  },
  {
    "No. of Connections": 1391,
    "Posts(past month)": 16,
    "Check Ins(past month)": 2,
    Sponsorships: 0,
    Total: 42.865,
    Rating: "BB",
  },
  {
    "No. of Connections": 997,
    "Posts(past month)": 8,
    "Check Ins(past month)": 6,
    Sponsorships: 0,
    Total: 40.955,
    Rating: "BB",
  },
  {
    "No. of Connections": 488,
    "Posts(past month)": 10,
    "Check Ins(past month)": 7,
    Sponsorships: 0,
    Total: 38.32,
    Rating: "B",
  },
  {
    "No. of Connections": 175,
    "Posts(past month)": 8,
    "Check Ins(past month)": 9,
    Sponsorships: 0,
    Total: 37.625,
    Rating: "B",
  },
  {
    "No. of Connections": 234,
    "Posts(past month)": 4,
    "Check Ins(past month)": 10,
    Sponsorships: 0,
    Total: 37.51,
    Rating: "B",
  },
  {
    "No. of Connections": 413,
    "Posts(past month)": 4,
    "Check Ins(past month)": 9,
    Sponsorships: 0,
    Total: 37.195,
    Rating: "B",
  },
  {
    "No. of Connections": 143,
    "Posts(past month)": 5,
    "Check Ins(past month)": 10,
    Sponsorships: 0,
    Total: 37.145,
    Rating: "B",
  },
  {
    "No. of Connections": 268,
    "Posts(past month)": 1,
    "Check Ins(past month)": 9,
    Sponsorships: 1,
    Total: 37.02,
    Rating: "B",
  },
  {
    "No. of Connections": 115,
    "Posts(past month)": 29,
    "Check Ins(past month)": 2,
    Sponsorships: 0,
    Total: 36.725,
    Rating: "B",
  },
  {
    "No. of Connections": 311,
    "Posts(past month)": 20,
    "Check Ins(past month)": 4,
    Sponsorships: 0,
    Total: 36.665,
    Rating: "B",
  },
  {
    "No. of Connections": 1998,
    "Posts(past month)": 6,
    "Check Ins(past month)": 0,
    Sponsorships: 0,
    Total: 35.97,
    Rating: "B",
  },
  {
    "No. of Connections": 514,
    "Posts(past month)": 5,
    "Check Ins(past month)": 6,
    Sponsorships: 1,
    Total: 35.71,
    Rating: "B",
  },
  {
    "No. of Connections": 306,
    "Posts(past month)": 19,
    "Check Ins(past month)": 4,
    Sponsorships: 0,
    Total: 35.59,
    Rating: "B",
  },
  {
    "No. of Connections": 362,
    "Posts(past month)": 0,
    "Check Ins(past month)": 10,
    Sponsorships: 0,
    Total: 35.43,
    Rating: "B",
  },
  {
    "No. of Connections": 472,
    "Posts(past month)": 19,
    "Check Ins(past month)": 3,
    Sponsorships: 0,
    Total: 35.08,
    Rating: "B",
  },
  {
    "No. of Connections": 1186,
    "Posts(past month)": 12,
    "Check Ins(past month)": 0,
    Sponsorships: 1,
    Total: 34.79,
    Rating: "B",
  },
  {
    "No. of Connections": 578,
    "Posts(past month)": 12,
    "Check Ins(past month)": 3,
    Sponsorships: 1,
    Total: 34.67,
    Rating: "B",
  },
  {
    "No. of Connections": 708,
    "Posts(past month)": 6,
    "Check Ins(past month)": 6,
    Sponsorships: 0,
    Total: 34.62,
    Rating: "B",
  },
  {
    "No. of Connections": 152,
    "Posts(past month)": 14,
    "Check Ins(past month)": 6,
    Sponsorships: 0,
    Total: 34.28,
    Rating: "B",
  },
  {
    "No. of Connections": 674,
    "Posts(past month)": 21,
    "Check Ins(past month)": 1,
    Sponsorships: 0,
    Total: 34.11,
    Rating: "B",
  },
  {
    "No. of Connections": 498,
    "Posts(past month)": 22,
    "Check Ins(past month)": 1,
    Sponsorships: 0,
    Total: 32.47,
    Rating: "B",
  },
  {
    "No. of Connections": 459,
    "Posts(past month)": 19,
    "Check Ins(past month)": 1,
    Sponsorships: 0,
    Total: 28.885,
    Rating: "B",
  },
  {
    "No. of Connections": 498,
    "Posts(past month)": 8,
    "Check Ins(past month)": 4,
    Sponsorships: 0,
    Total: 27.47,
    Rating: "B",
  },
  {
    "No. of Connections": 487,
    "Posts(past month)": 13,
    "Check Ins(past month)": 2,
    Sponsorships: 0,
    Total: 26.305,
    Rating: "B",
  },
  {
    "No. of Connections": 114,
    "Posts(past month)": 3,
    "Check Ins(past month)": 7,
    Sponsorships: 0,
    Total: 25.71,
    Rating: "B",
  },
  {
    "No. of Connections": 308,
    "Posts(past month)": 3,
    "Check Ins(past month)": 6,
    Sponsorships: 0,
    Total: 25.62,
    Rating: "B",
  },
  {
    "No. of Connections": 1321,
    "Posts(past month)": 4,
    "Check Ins(past month)": 0,
    Sponsorships: 0,
    Total: 23.815,
    Rating: "B",
  },
  {
    "No. of Connections": 581,
    "Posts(past month)": 12,
    "Check Ins(past month)": 1,
    Sponsorships: 0,
    Total: 23.715,
    Rating: "B",
  },
  {
    "No. of Connections": 229,
    "Posts(past month)": 4,
    "Check Ins(past month)": 5,
    Sponsorships: 0,
    Total: 22.435,
    Rating: "B",
  },
  {
    "No. of Connections": 299,
    "Posts(past month)": 9,
    "Check Ins(past month)": 2,
    Sponsorships: 0,
    Total: 19.485,
    Rating: "B",
  },
  {
    "No. of Connections": 220,
    "Posts(past month)": 12,
    "Check Ins(past month)": 1,
    Sponsorships: 0,
    Total: 18.3,
    Rating: "B",
  },
  {
    "No. of Connections": 440,
    "Posts(past month)": 1,
    "Check Ins(past month)": 3,
    Sponsorships: 0,
    Total: 16.6,
    Rating: "B",
  },
  {
    "No. of Connections": 760,
    "Posts(past month)": 1,
    "Check Ins(past month)": 1,
    Sponsorships: 0,
    Total: 15.4,
    Rating: "B",
  },
  {
    "No. of Connections": 244,
    "Posts(past month)": 11,
    "Check Ins(past month)": 0,
    Sponsorships: 0,
    Total: 14.66,
    Rating: "B",
  },
  {
    "No. of Connections": 588,
    "Posts(past month)": 1,
    "Check Ins(past month)": 1,
    Sponsorships: 0,
    Total: 12.82,
    Rating: "B",
  },
];
