export const data = [
  {
    Hometown: 1,
    "Current Town": 1,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 3,
    "Credit Score": 230,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 3,
    "Credit Score": 215,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 2,
    "Credit Score": 205,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 2,
    "Credit Score": 205,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 1,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 0,
    "Credit Score": 200,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 200,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 3,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 3,
    "Credit Score": 200,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 200,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 3,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 3,
    "Credit Score": 200,
    Rating: "AA",
  },
  {
    Hometown: 2,
    "Current Town": 1,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 3,
    "Credit Score": 200,
    Rating: "AA",
  },
  {
    Hometown: 2,
    "Current Town": 1,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 3,
    "Credit Score": 200,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 200,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 2,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 195,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 1,
    "Credit Score": 195,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 2,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 195,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 1,
    "Credit Score": 195,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 190,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 190,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 1,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 190,
    Rating: "AA",
  },
  {
    Hometown: 2,
    "Current Town": 1,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 2,
    "Credit Score": 190,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 2,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 185,
    Rating: "AA",
  },
  {
    Hometown: 2,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 3,
    "Credit Score": 185,
    Rating: "AA",
  },
  {
    Hometown: 2,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 3,
    "Credit Score": 185,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 0,
    "Credit Score": 185,
    Rating: "AA",
  },
  {
    Hometown: 2,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 180,
    Rating: "AA",
  },
  {
    Hometown: 2,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 180,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 180,
    Rating: "AA",
  },
  {
    Hometown: 2,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 180,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 3,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 180,
    Rating: "AA",
  },
  {
    Hometown: 1,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 2,
    "Credit Score": 175,
    Rating: "A",
  },
  {
    Hometown: 1,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 2,
    "Credit Score": 175,
    Rating: "A",
  },
  {
    Hometown: 1,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 175,
    Rating: "A",
  },
  {
    Hometown: 1,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 2,
    "Credit Score": 175,
    Rating: "A",
  },
  {
    Hometown: 1,
    "Current Town": 3,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 170,
    Rating: "A",
  },
  {
    Hometown: 3,
    "Current Town": 1,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 3,
    "Credit Score": 170,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 170,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 1,
    "Credit Score": 165,
    Rating: "A",
  },
  {
    Hometown: 1,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 165,
    Rating: "A",
  },
  {
    Hometown: 1,
    "Current Town": 2,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 165,
    Rating: "A",
  },
  {
    Hometown: 1,
    "Current Town": 3,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 160,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 160,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 160,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 1,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 160,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 0,
    "Credit Score": 155,
    Rating: "A",
  },
  {
    Hometown: 1,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 155,
    Rating: "A",
  },
  {
    Hometown: 1,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 155,
    Rating: "A",
  },
  {
    Hometown: 3,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 150,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 3,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 150,
    Rating: "A",
  },
  {
    Hometown: 3,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 150,
    Rating: "A",
  },
  {
    Hometown: 1,
    "Current Town": 3,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 150,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 150,
    Rating: "A",
  },
  {
    Hometown: 1,
    "Current Town": 3,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 150,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 2,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 145,
    Rating: "A",
  },
  {
    Hometown: 3,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 2,
    "Credit Score": 145,
    Rating: "A",
  },
  {
    Hometown: 1,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 145,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 145,
    Rating: "A",
  },
  {
    Hometown: 1,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 145,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 145,
    Rating: "A",
  },
  {
    Hometown: 3,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 140,
    Rating: "A",
  },
  {
    Hometown: 3,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 140,
    Rating: "A",
  },
  {
    Hometown: 3,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 140,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 135,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 135,
    Rating: "A",
  },
  {
    Hometown: 3,
    "Current Town": 2,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 135,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 135,
    Rating: "A",
  },
  {
    Hometown: 1,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 1,
    OTT: 0,
    "Credit Score": 135,
    Rating: "A",
  },
  {
    Hometown: 3,
    "Current Town": 2,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 135,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 2,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 135,
    Rating: "A",
  },
  {
    Hometown: 4,
    "Current Town": 1,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 2,
    "Credit Score": 130,
    Rating: "A",
  },
  {
    Hometown: 3,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 130,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 3,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 130,
    Rating: "A",
  },
  {
    Hometown: 3,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 130,
    Rating: "A",
  },
  {
    Hometown: 3,
    "Current Town": 1,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 130,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 3,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 130,
    Rating: "A",
  },
  {
    Hometown: 3,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 130,
    Rating: "A",
  },
  {
    Hometown: 2,
    "Current Town": 3,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 130,
    Rating: "A",
  },
  {
    Hometown: 3,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 0,
    "Credit Score": 125,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 0,
    "Credit Score": 125,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 3,
    "Credit Score": 125,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 2,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 125,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 2,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 125,
    Rating: "BB",
  },
  {
    Hometown: 2,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 0,
    "Credit Score": 125,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 2,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 125,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 1,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 120,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 120,
    Rating: "BB",
  },
  {
    Hometown: 2,
    "Current Town": 3,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 120,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 120,
    Rating: "BB",
  },
  {
    Hometown: 2,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 115,
    Rating: "BB",
  },
  {
    Hometown: 2,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 115,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 2,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 115,
    Rating: "BB",
  },
  {
    Hometown: 1,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 115,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 2,
    "Credit Score": 115,
    Rating: "BB",
  },
  {
    Hometown: 2,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 115,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 1,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 110,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 3,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 0,
    "Credit Score": 110,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 1,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 110,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 2,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 105,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 2,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 105,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 105,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 2,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 105,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 1,
    "Credit Score": 105,
    Rating: "BB",
  },
  {
    Hometown: 2,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 105,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 105,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 1,
    "Credit Score": 105,
    Rating: "BB",
  },
  {
    Hometown: 2,
    "Current Town": 3,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 100,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 1,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 100,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 3,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 2,
    "Credit Score": 100,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 1,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 100,
    Rating: "BB",
  },
  {
    Hometown: 2,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 95,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 0,
    "Credit Score": 95,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 3,
    "Credit Score": 95,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 95,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 95,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 0,
    "Credit Score": 95,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 3,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 90,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 3,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 1,
    "Credit Score": 90,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 1,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 90,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 3,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 90,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 3,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 90,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 3,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 90,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 3,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 90,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 85,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 85,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 85,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 85,
    Rating: "BB",
  },
  {
    Hometown: 4,
    "Current Town": 3,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 0,
    "Credit Score": 80,
    Rating: "BB",
  },
  {
    Hometown: 3,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 75,
    Rating: "B",
  },
  {
    Hometown: 4,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 1,
    "Credit Score": 75,
    Rating: "B",
  },
  {
    Hometown: 3,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 75,
    Rating: "B",
  },
  {
    Hometown: 4,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 1,
    "Credit Score": 75,
    Rating: "B",
  },
  {
    Hometown: 3,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 75,
    Rating: "B",
  },
  {
    Hometown: 3,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 75,
    Rating: "B",
  },
  {
    Hometown: 4,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 1,
    "Credit Score": 75,
    Rating: "B",
  },
  {
    Hometown: 4,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 1,
    "Credit Score": 75,
    Rating: "B",
  },
  {
    Hometown: 4,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 75,
    Rating: "B",
  },
  {
    Hometown: 3,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 75,
    Rating: "B",
  },
  {
    Hometown: 4,
    "Current Town": 2,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 75,
    Rating: "B",
  },
  {
    Hometown: 4,
    "Current Town": 3,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 3,
    "Credit Score": 70,
    Rating: "B",
  },
  {
    Hometown: 4,
    "Current Town": 1,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 70,
    Rating: "B",
  },
  {
    Hometown: 3,
    "Current Town": 3,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 70,
    Rating: "B",
  },
  {
    Hometown: 4,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 65,
    Rating: "B",
  },
  {
    Hometown: 4,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 1,
    OTT: 0,
    "Credit Score": 65,
    Rating: "B",
  },
  {
    Hometown: 4,
    "Current Town": 3,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 2,
    "Credit Score": 60,
    Rating: "B",
  },
  {
    Hometown: 4,
    "Current Town": 3,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 60,
    Rating: "B",
  },
  {
    Hometown: 4,
    "Current Town": 3,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 60,
    Rating: "B",
  },
  {
    Hometown: 3,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 55,
    Rating: "B",
  },
  {
    Hometown: 4,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 1,
    "Credit Score": 55,
    Rating: "B",
  },
  {
    Hometown: 3,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 55,
    Rating: "B",
  },
  {
    Hometown: 4,
    "Current Town": 4,
    "Martial Status": 0,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 45,
    Rating: "B",
  },
  {
    Hometown: 4,
    "Current Town": 4,
    "Martial Status": 1,
    "Spouse job": 0,
    OTT: 0,
    "Credit Score": 25,
    Rating: "B",
  },
];
